[package]
description = "Parity Updater Service."
name = "parity-updater"
version = "1.9.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
log = "0.3"
# ethabi = { git = "https://github.com/paritytech/ethabi/", branch = "call-function" } # "4.0"
# ethabi-derive = { git = "https://github.com/paritytech/ethabi/", branch = "call-function" } # "4.0"
# ethabi-contract = { git = "https://github.com/paritytech/ethabi/", branch = "call-function" } # "4.0"
ethabi = { path = "/home/xx/web/ethabi/ethabi" } # "4.0"
ethabi-derive = { path = "/home/xx/web/ethabi/derive" } # "4.0"
ethabi-contract = { path = "/home/xx/web/ethabi/contract" } # "4.0"
target_info = "0.1"
semver = "0.6"
ethcore = { path = "../ethcore" }
ethsync = { path = "../sync" }
ethcore-util = { path = "../util" }
ethcore-bigint = { path = "../util/bigint" }
ethcore-bytes = { path = "../util/bytes" }
futures = "0.1"
parking_lot = "0.4"
parity-hash-fetch = { path = "../hash-fetch" }
parity-reactor = { path = "../util/reactor" }
path = { path = "../util/path" }

[dev-dependencies]
parity-rpc = { path = "../rpc" }
